# Generated by Django 3.2 on 2023-04-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30, unique=True)),
                ('iso3', models.CharField(max_length=100, null=True, verbose_name='iso3')),
                ('iso2', models.CharField(max_length=100, null=True, verbose_name='iso2')),
                ('numeric_code', models.CharField(max_length=10, verbose_name='numeric_code')),
                ('phone_code', models.CharField(max_length=200, verbose_name='phone_code')),
                ('capital', models.CharField(max_length=100, verbose_name='capital')),
                ('currency', models.CharField(max_length=10, verbose_name='currency')),
                ('currency_name', models.CharField(max_length=100, verbose_name='currency_name')),
                ('region', models.CharField(max_length=60, verbose_name='region')),
                ('subregion', models.CharField(max_length=100, verbose_name='subregion')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30, unique=True)),
                ('state_code', models.CharField(max_length=2, unique=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, null=True, verbose_name='longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_masters', to='app.countrymaster')),
            ],
        ),
        migrations.CreateModel(
            name='CountryTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=255)),
                ('gmtOffset', models.CharField(max_length=255)),
                ('gmtOffsetName', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('tzName', models.CharField(max_length=255)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_master_zones', to='app.countrymaster')),
            ],
        ),
    ]
