# Generated by Django 3.2 on 2023-04-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_queryfromcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryfromcontact',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='queryfromcontact',
            name='subject',
        ),
    ]
