# Generated by Django 3.2 on 2023-04-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
